version: '3.8'
services:
#  db:
#    image: mcr.microsoft.com/mssql/server:2022-latest
#    platform: linux/amd64
#    env_file:
#      - ../../backend/.env
#    environment:
#      - ACCEPT_EULA=Y
#    ports:
#      - "1433:1433"
#    expose:
#      - "1433"
#    volumes:
#      - ./data:/var/opt/mssql
  backend:
    build:
      context: ../../
      dockerfile: docker/dockerfile/dev.Dockerfile
    volumes:
      - ../../backend:/app:cached
      - .:/app
      - /app/node_modules/bcrypt/
    ports:
      - "8000:8000"
    env_file:
      - ../../backend/dev.env
    environment:
      - DB_HOST=db
